export interface Company {
  id: string
  name: string
  slug: string
  description: string
  logo?: string
  website?: string
  industry: string
  size: "STARTUP" | "SMALL" | "MEDIUM" | "LARGE" | "ENTERPRISE"
  location: string
  verified: boolean
  founded?: number
  employees?: string
  benefits?: string[]
  culture?: string
  socialMedia?: {
    linkedin?: string
    twitter?: string
    facebook?: string
  }
  createdAt: Date
  updatedAt: Date
}

export const mockCompanies: Company[] = [
  {
    id: "techcorp",
    name: "TechCorp Inc.",
    slug: "techcorp-inc",
    description: "A leading technology company specializing in cloud computing and enterprise software solutions. We help businesses transform their operations through innovative technology.",
    logo: "https://via.placeholder.com/120x120/3B82F6/FFFFFF?text=TC",
    website: "https://techcorp.com",
    industry: "Technology",
    size: "LARGE",
    location: "San Francisco, CA",
    verified: true,
    founded: 2010,
    employees: "1,000-5,000",
    benefits: ["Health Insurance", "401(k) Match", "Flexible PTO", "Remote Work", "Stock Options"],
    culture: "Innovation-driven culture with focus on work-life balance and continuous learning.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/techcorp",
      twitter: "https://twitter.com/techcorp",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "microsoft",
    name: "Microsoft",
    slug: "microsoft",
    description: "Global technology leader empowering every person and organization on the planet to achieve more through innovative software, services, and hardware.",
    logo: "https://via.placeholder.com/120x120/00BCF2/FFFFFF?text=MS",
    website: "https://microsoft.com",
    industry: "Technology",
    size: "ENTERPRISE",
    location: "Redmond, WA",
    verified: true,
    founded: 1975,
    employees: "100,000+",
    benefits: ["Comprehensive Healthcare", "Retirement Plans", "Education Assistance", "Parental Leave", "Wellness Programs"],
    culture: "Inclusive culture that values diversity, growth mindset, and collaboration across all teams.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/microsoft",
      twitter: "https://twitter.com/microsoft",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "google",
    name: "Google",
    slug: "google",
    description: "Organizing the world's information and making it universally accessible and useful through innovative search, advertising, and cloud technologies.",
    logo: "https://via.placeholder.com/120x120/4285F4/FFFFFF?text=G",
    website: "https://google.com",
    industry: "Technology",
    size: "ENTERPRISE",
    location: "Mountain View, CA",
    verified: true,
    founded: 1998,
    employees: "100,000+",
    benefits: ["Health & Wellness", "Financial Benefits", "Time Off", "Family Support", "Development Opportunities"],
    culture: "Data-driven culture focused on innovation, collaboration, and making a positive impact on the world.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/google",
      twitter: "https://twitter.com/google",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "amazon",
    name: "Amazon",
    slug: "amazon",
    description: "Earth's most customer-centric company, offering everything from e-commerce to cloud computing, logistics, and digital entertainment.",
    logo: "https://via.placeholder.com/120x120/FF9900/FFFFFF?text=A",
    website: "https://amazon.com",
    industry: "Technology/E-commerce",
    size: "ENTERPRISE",
    location: "Seattle, WA",
    verified: true,
    founded: 1994,
    employees: "1,000,000+",
    benefits: ["Medical Coverage", "401(k) Plan", "Paid Time Off", "Career Choice", "Employee Discount"],
    culture: "Customer-obsessed culture with high standards, ownership mentality, and long-term thinking.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/amazon",
      twitter: "https://twitter.com/amazon",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "meta",
    name: "Meta",
    slug: "meta",
    description: "Building the future of social connection through virtual and augmented reality, connecting billions of people worldwide.",
    logo: "https://via.placeholder.com/120x120/1877F2/FFFFFF?text=M",
    website: "https://meta.com",
    industry: "Technology/Social Media",
    size: "ENTERPRISE",
    location: "Menlo Park, CA",
    verified: true,
    founded: 2004,
    employees: "50,000-100,000",
    benefits: ["Health Benefits", "Equity Compensation", "Paid Time Off", "Professional Development", "Wellness Programs"],
    culture: "Move fast, be bold, and focus on long-term impact while building meaningful connections.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/meta",
      twitter: "https://twitter.com/meta",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "netflix",
    name: "Netflix",
    slug: "netflix",
    description: "World's leading streaming entertainment service with over 230 million paid memberships in more than 190 countries.",
    logo: "https://via.placeholder.com/120x120/E50914/FFFFFF?text=N",
    website: "https://netflix.com",
    industry: "Entertainment/Technology",
    size: "LARGE",
    location: "Los Gatos, CA",
    verified: true,
    founded: 1997,
    employees: "10,000-50,000",
    benefits: ["Unlimited PTO", "Health Insurance", "Stock Options", "Parental Leave", "Learning Budget"],
    culture: "Freedom and responsibility culture with high performance standards and innovative thinking.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/netflix",
      twitter: "https://twitter.com/netflix",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "tesla",
    name: "Tesla",
    slug: "tesla",
    description: "Accelerating the world's transition to sustainable energy through electric vehicles, energy storage, and solar panels.",
    logo: "https://via.placeholder.com/120x120/CC0000/FFFFFF?text=T",
    website: "https://tesla.com",
    industry: "Automotive/Clean Energy",
    size: "LARGE",
    location: "Austin, TX",
    verified: true,
    founded: 2003,
    employees: "100,000+",
    benefits: ["Health Benefits", "Stock Purchase Plan", "Paid Time Off", "Family Support", "Learning Opportunities"],
    culture: "Fast-paced, mission-driven environment focused on sustainable technology and innovation.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/tesla-motors",
      twitter: "https://twitter.com/tesla",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "startup-ai",
    name: "AI Innovations",
    slug: "ai-innovations",
    description: "Cutting-edge AI startup developing next-generation machine learning solutions for enterprise clients.",
    logo: "https://via.placeholder.com/120x120/8B5CF6/FFFFFF?text=AI",
    website: "https://ai-innovations.com",
    industry: "Artificial Intelligence",
    size: "STARTUP",
    location: "San Francisco, CA",
    verified: false,
    founded: 2022,
    employees: "10-50",
    benefits: ["Equity Package", "Health Insurance", "Flexible Hours", "Learning Budget", "Catered Meals"],
    culture: "Fast-growing startup culture with emphasis on innovation, learning, and rapid iteration.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/ai-innovations",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "healthtech",
    name: "HealthTech Solutions",
    slug: "healthtech-solutions",
    description: "Digital health platform improving patient outcomes through innovative healthcare technology and data analytics.",
    logo: "https://via.placeholder.com/120x120/10B981/FFFFFF?text=HT",
    website: "https://healthtech-solutions.com",
    industry: "Healthcare Technology",
    size: "MEDIUM",
    location: "Boston, MA",
    verified: true,
    founded: 2018,
    employees: "200-500",
    benefits: ["Health Insurance", "401(k) Match", "Remote Work", "Professional Development", "Wellness Programs"],
    culture: "Mission-driven culture focused on improving healthcare outcomes and work-life balance.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/healthtech-solutions",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "fintech-pro",
    name: "FinTech Pro",
    slug: "fintech-pro",
    description: "Revolutionary fintech company providing innovative payment solutions and financial services to businesses worldwide.",
    logo: "https://via.placeholder.com/120x120/F59E0B/FFFFFF?text=FP",
    website: "https://fintech-pro.com",
    industry: "Financial Technology",
    size: "MEDIUM",
    location: "New York, NY",
    verified: true,
    founded: 2019,
    employees: "100-500",
    benefits: ["Competitive Salary", "Stock Options", "Health Benefits", "Flexible PTO", "Learning Stipend"],
    culture: "Data-driven culture with focus on innovation, compliance, and customer-first approach.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/fintech-pro",
      twitter: "https://twitter.com/fintechpro",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "ecommerce-plus",
    name: "E-Commerce Plus",
    slug: "ecommerce-plus",
    description: "Leading e-commerce platform helping small and medium businesses build successful online stores.",
    logo: "https://via.placeholder.com/120x120/EC4899/FFFFFF?text=EP",
    website: "https://ecommerce-plus.com",
    industry: "E-commerce",
    size: "MEDIUM",
    location: "Austin, TX",
    verified: true,
    founded: 2017,
    employees: "300-1000",
    benefits: ["Health Coverage", "401(k)", "Unlimited PTO", "Remote Work", "Education Reimbursement"],
    culture: "Collaborative environment with emphasis on customer success and continuous improvement.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/ecommerce-plus",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "design-studio",
    name: "Creative Design Studio",
    slug: "creative-design-studio",
    description: "Award-winning design agency creating exceptional digital experiences for brands worldwide.",
    logo: "https://via.placeholder.com/120x120/06B6D4/FFFFFF?text=CDS",
    website: "https://creative-design-studio.com",
    industry: "Design/Creative",
    size: "SMALL",
    location: "Portland, OR",
    verified: true,
    founded: 2015,
    employees: "50-100",
    benefits: ["Health Insurance", "Creative Freedom", "Flexible Schedule", "Professional Development", "Team Retreats"],
    culture: "Creative-first culture with emphasis on artistic expression and client collaboration.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/creative-design-studio",
      twitter: "https://twitter.com/creativeds",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "consulting-group",
    name: "Strategic Consulting Group",
    slug: "strategic-consulting-group",
    description: "Management consulting firm helping Fortune 500 companies solve complex business challenges.",
    logo: "https://via.placeholder.com/120x120/374151/FFFFFF?text=SCG",
    website: "https://strategic-consulting.com",
    industry: "Consulting",
    size: "LARGE",
    location: "Chicago, IL",
    verified: true,
    founded: 2005,
    employees: "1000-5000",
    benefits: ["Premium Health Care", "Performance Bonus", "Travel Opportunities", "MBA Sponsorship", "Sabbatical Leave"],
    culture: "High-performance culture with emphasis on analytical thinking and client excellence.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/strategic-consulting-group",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "green-energy",
    name: "Green Energy Corp",
    slug: "green-energy-corp",
    description: "Sustainable energy company developing renewable energy solutions for a cleaner future.",
    logo: "https://via.placeholder.com/120x120/22C55E/FFFFFF?text=GE",
    website: "https://green-energy-corp.com",
    industry: "Renewable Energy",
    size: "MEDIUM",
    location: "Denver, CO",
    verified: true,
    founded: 2016,
    employees: "200-500",
    benefits: ["Health Benefits", "Green Commute Allowance", "Sabbatical Options", "Stock Options", "Wellness Programs"],
    culture: "Environmentally conscious culture with focus on sustainability and social responsibility.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/green-energy-corp",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "robotics-lab",
    name: "Advanced Robotics Lab",
    slug: "advanced-robotics-lab",
    description: "Research and development company creating next-generation robotics solutions for industrial applications.",
    logo: "https://via.placeholder.com/120x120/6366F1/FFFFFF?text=AR",
    website: "https://advanced-robotics-lab.com",
    industry: "Robotics/Manufacturing",
    size: "SMALL",
    location: "Pittsburgh, PA",
    verified: true,
    founded: 2020,
    employees: "50-200",
    benefits: ["Health Insurance", "Research Budget", "Conference Attendance", "Patent Bonuses", "Flexible Hours"],
    culture: "Research-driven environment with focus on innovation and technical excellence.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/advanced-robotics-lab",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "biotech-solutions",
    name: "BioTech Solutions",
    slug: "biotech-solutions",
    description: "Biotechnology company developing innovative treatments and diagnostic tools for precision medicine.",
    logo: "https://via.placeholder.com/120x120/EF4444/FFFFFF?text=BT",
    website: "https://biotech-solutions.com",
    industry: "Biotechnology",
    size: "MEDIUM",
    location: "Cambridge, MA",
    verified: true,
    founded: 2014,
    employees: "100-500",
    benefits: ["Health Coverage", "Research Sabbatical", "Stock Options", "Professional Development", "Lab Equipment Access"],
    culture: "Science-driven culture with emphasis on breakthrough research and collaboration.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/biotech-solutions",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "marketing-agency",
    name: "Digital Marketing Agency",
    slug: "digital-marketing-agency",
    description: "Full-service digital marketing agency helping brands grow through data-driven marketing strategies.",
    logo: "https://via.placeholder.com/120x120/F97316/FFFFFF?text=DM",
    website: "https://digital-marketing-agency.com",
    industry: "Marketing/Advertising",
    size: "SMALL",
    location: "Miami, FL",
    verified: true,
    founded: 2019,
    employees: "25-100",
    benefits: ["Health Insurance", "Creative Days", "Client Entertainment", "Skill Training", "Flexible PTO"],
    culture: "Creative and results-driven culture with emphasis on innovation and client success.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/digital-marketing-agency",
      twitter: "https://twitter.com/digitalmarketing",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "cybersecurity-firm",
    name: "CyberSecurity Pro",
    slug: "cybersecurity-pro",
    description: "Leading cybersecurity firm protecting organizations from advanced threats and security breaches.",
    logo: "https://via.placeholder.com/120x120/1F2937/FFFFFF?text=CS",
    website: "https://cybersecurity-pro.com",
    industry: "Cybersecurity",
    size: "MEDIUM",
    location: "Washington, DC",
    verified: true,
    founded: 2013,
    employees: "300-1000",
    benefits: ["Security Clearance Bonus", "Health Benefits", "Continuous Training", "Conference Budget", "Remote Work"],
    culture: "Security-first culture with emphasis on continuous learning and threat awareness.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/cybersecurity-pro",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "data-analytics",
    name: "Data Analytics Inc",
    slug: "data-analytics-inc",
    description: "Data analytics company helping businesses make informed decisions through advanced data science and visualization.",
    logo: "https://via.placeholder.com/120x120/7C3AED/FFFFFF?text=DA",
    website: "https://data-analytics-inc.com",
    industry: "Data Analytics",
    size: "MEDIUM",
    location: "Minneapolis, MN",
    verified: true,
    founded: 2017,
    employees: "100-300",
    benefits: ["Health Insurance", "Data Tools Access", "Conference Attendance", "Learning Budget", "Flexible Schedule"],
    culture: "Data-driven culture with emphasis on analytical thinking and continuous improvement.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/data-analytics-inc",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "cloud-services",
    name: "Cloud Services Pro",
    slug: "cloud-services-pro",
    description: "Cloud infrastructure company providing scalable cloud solutions and managed services to enterprises.",
    logo: "https://via.placeholder.com/120x120/0EA5E9/FFFFFF?text=CP",
    website: "https://cloud-services-pro.com",
    industry: "Cloud Computing",
    size: "LARGE",
    location: "Dallas, TX",
    verified: true,
    founded: 2012,
    employees: "500-2000",
    benefits: ["Health Coverage", "Cloud Certifications", "Stock Options", "Remote Work", "Professional Development"],
    culture: "Technology-focused culture with emphasis on scalability and customer reliability.",
    socialMedia: {
      linkedin: "https://linkedin.com/company/cloud-services-pro",
    },
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-12-01"),
  },
]