export interface Job {
  id: string
  title: string
  slug: string
  description: string
  requirements: string
  benefits: string
  location: string
  remote: boolean
  salaryMin?: number
  salaryMax?: number
  currency: string
  jobType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "FREELANCE" | "INTERNSHIP"
  experience: "ENTRY_LEVEL" | "MID_LEVEL" | "SENIOR_LEVEL" | "EXECUTIVE"
  status: "DRAFT" | "PUBLISHED" | "CLOSED" | "ARCHIVED"
  featured: boolean
  companyId: string
  categoryId: string
  views: number
  publishedAt?: Date
  expiresAt?: Date
  createdAt: Date
  updatedAt: Date
}

export const mockJobs: Job[] = [
  // Technology Jobs
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    slug: "senior-frontend-developer-1",
    description: "We're looking for a senior frontend developer to join our growing team. You'll be working on cutting-edge web applications using React, TypeScript, and modern tooling. This role offers the opportunity to lead technical decisions, mentor junior developers, and contribute to our design system. You'll collaborate closely with designers, product managers, and backend engineers to deliver exceptional user experiences.",
    requirements: "5+ years of experience with React and TypeScript\n• Strong knowledge of modern JavaScript ES6+\n• Experience with state management (Redux, Zustand)\n• Proficiency in CSS and responsive design\n• Experience with testing frameworks (Jest, React Testing Library)\n• Knowledge of build tools (Webpack, Vite)\n• Understanding of accessibility best practices\n• Experience with Git and agile methodologies",
    benefits: "• Competitive salary ($120k - $150k)\n• Comprehensive health, dental, and vision insurance\n• 401(k) with company match\n• Flexible working hours and remote options\n• Professional development budget ($3k/year)\n• Stock options\n• Unlimited PTO\n• Top-tier equipment and home office stipend",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 120000,
    salaryMax: 150000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "techcorp",
    categoryId: "cat-frontend",
    views: 245,
    publishedAt: new Date("2024-12-28"),
    expiresAt: new Date("2025-02-28"),
    createdAt: new Date("2024-12-28"),
    updatedAt: new Date("2024-12-30"),
  },
  {
    id: "job-2",
    title: "Product Manager",
    slug: "product-manager-2",
    description: "Lead product strategy and execution for our innovative platform. Work closely with engineering, design, and business teams to deliver exceptional user experiences. Define product roadmaps, analyze user feedback, and drive data-driven decisions to achieve business objectives. This role requires strong analytical skills and the ability to communicate effectively with stakeholders at all levels.",
    requirements: "3+ years of product management experience\n• Strong analytical and problem-solving skills\n• Experience with product analytics tools (Mixpanel, Amplitude)\n• Knowledge of user research methodologies\n• Excellent communication and presentation skills\n• Experience with agile development processes\n• Bachelor's degree in Business, Engineering, or related field\n• MBA preferred but not required",
    benefits: "• Competitive salary with equity package\n• Health insurance with premium coverage\n• Unlimited PTO policy\n• Professional development opportunities\n• Conference and training budget\n• Remote work flexibility\n• Stock options with high growth potential\n• Collaborative and innovative work environment",
    location: "Remote",
    remote: true,
    salaryMin: 100000,
    salaryMax: 130000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "startup-ai",
    categoryId: "cat-marketing",
    views: 89,
    publishedAt: new Date("2024-12-25"),
    expiresAt: new Date("2025-02-25"),
    createdAt: new Date("2024-12-25"),
    updatedAt: new Date("2024-12-25"),
  },
  {
    id: "job-3",
    title: "UX Designer",
    slug: "ux-designer-3",
    description: "Create intuitive and engaging user experiences for our digital products. Conduct user research, create wireframes and prototypes, and collaborate with product and engineering teams. You'll be responsible for the entire design process from concept to implementation, ensuring our products are both beautiful and functional.",
    requirements: "3+ years of UX design experience\n• Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)\n• Strong portfolio demonstrating design process\n• Experience with user research and usability testing\n• Knowledge of design systems and component libraries\n• Understanding of accessibility standards\n• Bachelor's degree in Design, HCI, or related field\n• Excellent communication and collaboration skills",
    benefits: "• Competitive salary and benefits\n• Creative freedom and autonomy\n• Latest design tools and software\n• Professional development budget\n• Flexible work schedule\n• Beautiful office space with design-focused amenities\n• Team retreats and design conferences\n• Stock options",
    location: "New York, NY",
    remote: false,
    salaryMin: 85000,
    salaryMax: 110000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "design-studio",
    categoryId: "cat-design",
    views: 156,
    publishedAt: new Date("2024-12-27"),
    expiresAt: new Date("2025-02-27"),
    createdAt: new Date("2024-12-27"),
    updatedAt: new Date("2024-12-27"),
  },
  {
    id: "job-4",
    title: "Data Scientist",
    slug: "data-scientist-4",
    description: "Join our data team to extract insights from large datasets and build machine learning models that drive business decisions. Work with cross-functional teams to identify opportunities, develop predictive models, and create data visualization dashboards. This role offers the opportunity to work with cutting-edge technology and make a significant impact on our product strategy.",
    requirements: "Masters/PhD in Statistics, Mathematics, Computer Science, or related field\n• 4+ years of experience in data science or analytics\n• Strong programming skills in Python and R\n• Experience with ML frameworks (scikit-learn, TensorFlow, PyTorch)\n• Proficiency in SQL and database technologies\n• Experience with data visualization tools (Tableau, PowerBI, D3.js)\n• Strong statistical knowledge and experimental design\n• Excellent communication skills",
    benefits: "• Competitive salary ($130k - $160k)\n• Comprehensive benefits package\n• Research sabbatical opportunities\n• Access to high-performance computing resources\n• Conference attendance and training budget\n• Stock options\n• Flexible work arrangements\n• Collaborative research environment",
    location: "Boston, MA",
    remote: true,
    salaryMin: 130000,
    salaryMax: 160000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "healthtech",
    categoryId: "cat-data",
    views: 203,
    publishedAt: new Date("2024-12-26"),
    expiresAt: new Date("2025-03-26"),
    createdAt: new Date("2024-12-26"),
    updatedAt: new Date("2024-12-28"),
  },
  {
    id: "job-5",
    title: "DevOps Engineer",
    slug: "devops-engineer-5",
    description: "Build and maintain scalable infrastructure to support our growing platform. Implement CI/CD pipelines, manage cloud resources, and ensure system reliability and security. Work closely with development teams to optimize deployment processes and improve system performance.",
    requirements: "3+ years of DevOps or infrastructure experience\n• Strong knowledge of AWS or Azure cloud platforms\n• Experience with containerization (Docker, Kubernetes)\n• Proficiency in Infrastructure as Code (Terraform, CloudFormation)\n• Experience with CI/CD tools (Jenkins, GitLab CI, GitHub Actions)\n• Knowledge of monitoring and logging tools\n• Scripting skills in Python, Bash, or PowerShell\n• Understanding of security best practices",
    benefits: "• Competitive salary and equity\n• AWS/Azure certification support\n• Health and wellness benefits\n• Professional development opportunities\n• Remote work flexibility\n• High-performance equipment\n• On-call compensation\n• Stock options",
    location: "Austin, TX",
    remote: true,
    salaryMin: 110000,
    salaryMax: 140000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "cloud-services",
    categoryId: "cat-devops",
    views: 178,
    publishedAt: new Date("2024-12-24"),
    expiresAt: new Date("2025-02-24"),
    createdAt: new Date("2024-12-24"),
    updatedAt: new Date("2024-12-26"),
  },
  {
    id: "job-6",
    title: "Backend Developer",
    slug: "backend-developer-6",
    description: "Develop and maintain robust backend services and APIs that power our platform. Work with microservices architecture, implement security best practices, and optimize for performance and scalability. Collaborate with frontend developers and product teams to deliver high-quality features.",
    requirements: "3+ years of backend development experience\n• Strong proficiency in Node.js and Python\n• Experience with RESTful API design and development\n• Knowledge of database technologies (PostgreSQL, MongoDB)\n• Experience with microservices architecture\n• Understanding of security principles and practices\n• Familiarity with cloud platforms (AWS, GCP, Azure)\n• Experience with testing frameworks and methodologies",
    benefits: "• Competitive salary ($95k - $125k)\n• Comprehensive health benefits\n• Stock options\n• Flexible working hours\n• Professional development budget\n• Remote work options\n• Modern tech stack\n• Collaborative team environment",
    location: "Seattle, WA",
    remote: true,
    salaryMin: 95000,
    salaryMax: 125000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "microsoft",
    categoryId: "cat-backend",
    views: 134,
    publishedAt: new Date("2024-12-23"),
    expiresAt: new Date("2025-02-23"),
    createdAt: new Date("2024-12-23"),
    updatedAt: new Date("2024-12-25"),
  },
  {
    id: "job-7",
    title: "Mobile App Developer",
    slug: "mobile-app-developer-7",
    description: "Build native mobile applications for iOS and Android platforms. Work with React Native and native technologies to create seamless user experiences. Collaborate with designers and backend developers to implement new features and maintain existing applications.",
    requirements: "2+ years of mobile development experience\n• Proficiency in React Native or native iOS/Android development\n• Experience with mobile app deployment and store guidelines\n• Knowledge of mobile UI/UX principles\n• Experience with RESTful APIs and third-party integrations\n• Understanding of mobile security best practices\n• Familiarity with mobile testing frameworks\n• Strong debugging and problem-solving skills",
    benefits: "• Competitive salary\n• Health and dental insurance\n• Flexible work schedule\n• Latest mobile devices for testing\n• Professional development opportunities\n• Stock options\n• Remote work flexibility\n• Team building events",
    location: "Los Angeles, CA",
    remote: false,
    salaryMin: 80000,
    salaryMax: 105000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "startup-ai",
    categoryId: "cat-mobile",
    views: 92,
    publishedAt: new Date("2024-12-22"),
    expiresAt: new Date("2025-02-22"),
    createdAt: new Date("2024-12-22"),
    updatedAt: new Date("2024-12-24"),
  },
  {
    id: "job-8",
    title: "Full Stack Engineer",
    slug: "full-stack-engineer-8",
    description: "Work across the entire technology stack to build and maintain our web applications. From database design to user interface implementation, you'll have the opportunity to impact every aspect of our product. Join a collaborative team that values innovation and quality.",
    requirements: "4+ years of full-stack development experience\n• Proficiency in JavaScript/TypeScript and modern frameworks\n• Experience with both SQL and NoSQL databases\n• Knowledge of frontend frameworks (React, Vue, Angular)\n• Backend experience with Node.js, Python, or similar\n• Understanding of web security principles\n• Experience with version control and collaborative development\n• Strong problem-solving and debugging skills",
    benefits: "• Competitive salary ($105k - $135k)\n• Equity participation\n• Comprehensive benefits package\n• Professional development support\n• Flexible work arrangements\n• Modern development tools\n• Collaborative work environment\n• Growth opportunities",
    location: "Denver, CO",
    remote: true,
    salaryMin: 105000,
    salaryMax: 135000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "green-energy",
    categoryId: "cat-fullstack",
    views: 167,
    publishedAt: new Date("2024-12-21"),
    expiresAt: new Date("2025-03-21"),
    createdAt: new Date("2024-12-21"),
    updatedAt: new Date("2024-12-23"),
  },
  {
    id: "job-9",
    title: "Cybersecurity Analyst",
    slug: "cybersecurity-analyst-9",
    description: "Protect our organization from cyber threats through monitoring, analysis, and incident response. Implement security controls, conduct vulnerability assessments, and develop security policies. Work with a dedicated team to maintain our security posture and respond to emerging threats.",
    requirements: "2+ years of cybersecurity experience\n• Knowledge of security frameworks (NIST, ISO 27001)\n• Experience with security tools (SIEM, vulnerability scanners)\n• Understanding of network security principles\n• Familiarity with compliance requirements (SOC 2, GDPR)\n• Strong analytical and problem-solving skills\n• Security certifications preferred (Security+, CISSP)\n• Excellent communication skills",
    benefits: "• Competitive salary with security clearance bonus\n• Comprehensive benefits package\n• Continuous training and certification support\n• Conference attendance opportunities\n• Remote work options\n• Security clearance sponsorship\n• Professional development budget\n• Collaborative security team",
    location: "Washington, DC",
    remote: true,
    salaryMin: 90000,
    salaryMax: 115000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "cybersecurity-firm",
    categoryId: "cat-security",
    views: 143,
    publishedAt: new Date("2024-12-20"),
    expiresAt: new Date("2025-02-20"),
    createdAt: new Date("2024-12-20"),
    updatedAt: new Date("2024-12-22"),
  },
  {
    id: "job-10",
    title: "AI/ML Engineer",
    slug: "ai-ml-engineer-10",
    description: "Design and implement machine learning models to solve complex business problems. Work with large datasets, develop predictive algorithms, and deploy ML models to production. Collaborate with data scientists and engineers to bring AI solutions to market.",
    requirements: "3+ years of ML engineering experience\n• Strong programming skills in Python and/or R\n• Experience with ML frameworks (TensorFlow, PyTorch, scikit-learn)\n• Knowledge of deep learning architectures\n• Experience with cloud ML platforms (AWS SageMaker, GCP AI)\n• Understanding of MLOps and model deployment\n• Strong mathematical background in statistics and linear algebra\n• PhD in relevant field preferred",
    benefits: "• Competitive salary ($140k - $180k)\n• Equity package\n• Research sabbatical opportunities\n• GPU cluster access\n• Conference and publication support\n• Health and wellness benefits\n• Flexible work arrangements\n• Cutting-edge technology access",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 140000,
    salaryMax: 180000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "google",
    categoryId: "cat-ai",
    views: 289,
    publishedAt: new Date("2024-12-19"),
    expiresAt: new Date("2025-03-19"),
    createdAt: new Date("2024-12-19"),
    updatedAt: new Date("2024-12-21"),
  },
  
  // Marketing Jobs
  {
    id: "job-11",
    title: "Digital Marketing Manager",
    slug: "digital-marketing-manager-11",
    description: "Lead our digital marketing efforts across multiple channels to drive growth and engagement. Develop and execute marketing campaigns, analyze performance metrics, and optimize for ROI. Manage social media presence, content creation, and paid advertising campaigns.",
    requirements: "3+ years of digital marketing experience\n• Proficiency in Google Analytics, Google Ads, Facebook Ads\n• Experience with marketing automation tools\n• Strong analytical skills and data-driven mindset\n• Content creation and copywriting abilities\n• SEO and SEM knowledge\n• Experience with CRM systems\n• Bachelor's degree in Marketing or related field",
    benefits: "• Competitive salary ($70k - $90k)\n• Performance-based bonuses\n• Health and dental insurance\n• Professional development opportunities\n• Creative freedom in campaigns\n• Flexible work schedule\n• Marketing tools and software budget\n• Team collaboration and growth",
    location: "Miami, FL",
    remote: false,
    salaryMin: 70000,
    salaryMax: 90000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "marketing-agency",
    categoryId: "cat-marketing",
    views: 112,
    publishedAt: new Date("2024-12-18"),
    expiresAt: new Date("2025-02-18"),
    createdAt: new Date("2024-12-18"),
    updatedAt: new Date("2024-12-20"),
  },
  {
    id: "job-12",
    title: "Content Marketing Specialist",
    slug: "content-marketing-specialist-12",
    description: "Create compelling content that engages our audience and drives business results. Develop content strategies, write blog posts, create social media content, and collaborate with design teams to produce high-quality marketing materials.",
    requirements: "2+ years of content marketing experience\n• Excellent writing and editing skills\n• Experience with content management systems\n• Knowledge of SEO best practices\n• Social media marketing experience\n• Basic graphic design skills preferred\n• Understanding of content analytics\n• Bachelor's degree in Communications, Marketing, or English",
    benefits: "• Competitive salary\n• Creative work environment\n• Professional development budget\n• Flexible schedule\n• Content creation tools\n• Health benefits\n• Remote work options\n• Growth opportunities",
    location: "Remote",
    remote: true,
    salaryMin: 55000,
    salaryMax: 70000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "ecommerce-plus",
    categoryId: "cat-marketing",
    views: 87,
    publishedAt: new Date("2024-12-17"),
    expiresAt: new Date("2025-02-17"),
    createdAt: new Date("2024-12-17"),
    updatedAt: new Date("2024-12-19"),
  },
  
  // Sales Jobs
  {
    id: "job-13",
    title: "Sales Development Representative",
    slug: "sales-development-representative-13",
    description: "Generate qualified leads and build relationships with potential customers. Conduct outbound prospecting, qualify leads, and set up meetings for the sales team. This is an excellent opportunity to start your sales career with a growing company.",
    requirements: "1+ years of sales or customer service experience\n• Excellent communication and interpersonal skills\n• Strong phone and email communication abilities\n• CRM experience preferred (Salesforce, HubSpot)\n• Goal-oriented and self-motivated\n• Bachelor's degree preferred\n• Ability to handle rejection and maintain persistence\n• Coachable and eager to learn",
    benefits: "• Base salary plus commission ($50k - $75k OTE)\n• Comprehensive training program\n• Career advancement opportunities\n• Health and dental benefits\n• Sales incentives and bonuses\n• Modern sales tools and technology\n• Collaborative team environment\n• Performance recognition programs",
    location: "New York, NY",
    remote: false,
    salaryMin: 50000,
    salaryMax: 75000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "ENTRY_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "fintech-pro",
    categoryId: "cat-sales",
    views: 98,
    publishedAt: new Date("2024-12-16"),
    expiresAt: new Date("2025-02-16"),
    createdAt: new Date("2024-12-16"),
    updatedAt: new Date("2024-12-18"),
  },
  {
    id: "job-14",
    title: "Account Executive",
    slug: "account-executive-14",
    description: "Manage relationships with existing clients and drive revenue growth through upselling and cross-selling. Develop account strategies, conduct business reviews, and ensure customer success and satisfaction.",
    requirements: "3+ years of B2B sales experience\n• Proven track record of meeting sales quotas\n• Experience with enterprise clients\n• Strong presentation and negotiation skills\n• CRM proficiency (Salesforce preferred)\n• Understanding of consultative selling\n• Bachelor's degree in Business or related field\n• Travel flexibility for client meetings",
    benefits: "• Competitive base salary plus commission ($80k - $120k OTE)\n• Accelerated commission for overachievement\n• Health, dental, and vision insurance\n• Stock options\n• Professional development budget\n• Sales trips and incentives\n• Flexible work arrangements\n• Career growth opportunities",
    location: "Chicago, IL",
    remote: true,
    salaryMin: 80000,
    salaryMax: 120000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "consulting-group",
    categoryId: "cat-sales",
    views: 123,
    publishedAt: new Date("2024-12-15"),
    expiresAt: new Date("2025-02-15"),
    createdAt: new Date("2024-12-15"),
    updatedAt: new Date("2024-12-17"),
  },
  
  // Finance Jobs
  {
    id: "job-15",
    title: "Financial Analyst",
    slug: "financial-analyst-15",
    description: "Provide financial analysis and insights to support strategic business decisions. Prepare financial reports, conduct variance analysis, and assist with budgeting and forecasting processes. Work closely with various departments to analyze performance and identify improvement opportunities.",
    requirements: "2+ years of financial analysis experience\n• Strong proficiency in Excel and financial modeling\n• Knowledge of accounting principles (GAAP)\n• Experience with financial reporting and analysis\n• CPA or CFA certification preferred\n• Strong analytical and problem-solving skills\n• Excellent communication and presentation abilities\n• Bachelor's degree in Finance, Accounting, or Economics",
    benefits: "• Competitive salary ($65k - $85k)\n• Performance-based bonuses\n• Comprehensive benefits package\n• CPA/CFA exam support\n• Professional development opportunities\n• Flexible work arrangements\n• Retirement plan with matching\n• Health and wellness programs",
    location: "Boston, MA",
    remote: true,
    salaryMin: 65000,
    salaryMax: 85000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "biotech-solutions",
    categoryId: "cat-finance",
    views: 76,
    publishedAt: new Date("2024-12-14"),
    expiresAt: new Date("2025-02-14"),
    createdAt: new Date("2024-12-14"),
    updatedAt: new Date("2024-12-16"),
  },
  
  // Healthcare Jobs
  {
    id: "job-16",
    title: "Healthcare Data Analyst",
    slug: "healthcare-data-analyst-16",
    description: "Analyze healthcare data to improve patient outcomes and operational efficiency. Work with clinical teams to identify trends, develop reports, and support evidence-based decision making. Experience with healthcare systems and regulations required.",
    requirements: "2+ years of healthcare data analysis experience\n• Knowledge of healthcare systems and workflows\n• Proficiency in SQL, Python, or R\n• Experience with healthcare databases and EMR systems\n• Understanding of HIPAA and healthcare regulations\n• Strong statistical analysis skills\n• Healthcare degree or certification preferred\n• Excellent communication skills for clinical audiences",
    benefits: "• Competitive salary ($70k - $90k)\n• Comprehensive healthcare benefits\n• Professional development in healthcare analytics\n• Flexible work schedule\n• Meaningful work improving patient care\n• Conference attendance opportunities\n• Retirement plan with matching\n• Wellness programs",
    location: "Boston, MA",
    remote: true,
    salaryMin: 70000,
    salaryMax: 90000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "healthtech",
    categoryId: "cat-healthcare",
    views: 65,
    publishedAt: new Date("2024-12-13"),
    expiresAt: new Date("2025-02-13"),
    createdAt: new Date("2024-12-13"),
    updatedAt: new Date("2024-12-15"),
  },
  
  // Education Jobs
  {
    id: "job-17",
    title: "Learning and Development Specialist",
    slug: "learning-development-specialist-17",
    description: "Design and deliver training programs to enhance employee skills and development. Create learning materials, conduct workshops, and evaluate training effectiveness. Support career development and succession planning initiatives.",
    requirements: "3+ years of L&D or training experience\n• Experience with learning management systems (LMS)\n• Strong presentation and facilitation skills\n• Knowledge of adult learning principles\n• Content creation and instructional design abilities\n• Project management skills\n• Bachelor's degree in Education, HR, or related field\n• Training certifications preferred",
    benefits: "• Competitive salary ($60k - $80k)\n• Professional development budget\n• Health and wellness benefits\n• Flexible work schedule\n• Creative freedom in program design\n• Conference and training opportunities\n• Collaborative work environment\n• Growth opportunities",
    location: "Remote",
    remote: true,
    salaryMin: 60000,
    salaryMax: 80000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "data-analytics",
    categoryId: "cat-education",
    views: 54,
    publishedAt: new Date("2024-12-12"),
    expiresAt: new Date("2025-02-12"),
    createdAt: new Date("2024-12-12"),
    updatedAt: new Date("2024-12-14"),
  },
  
  // Operations Jobs
  {
    id: "job-18",
    title: "Operations Manager",
    slug: "operations-manager-18",
    description: "Oversee daily operations and improve operational efficiency across multiple departments. Develop and implement process improvements, manage vendor relationships, and ensure quality standards are met. Lead cross-functional projects and support business growth initiatives.",
    requirements: "5+ years of operations management experience\n• Strong project management and organizational skills\n• Experience with process improvement methodologies\n• Leadership and team management abilities\n• Data analysis and reporting skills\n• Vendor management experience\n• Bachelor's degree in Business, Operations, or related field\n• PMP certification preferred",
    benefits: "• Competitive salary ($85k - $110k)\n• Management development programs\n• Health and dental benefits\n• Performance bonuses\n• Stock options\n• Professional development support\n• Flexible work arrangements\n• Leadership training opportunities",
    location: "Dallas, TX",
    remote: false,
    salaryMin: 85000,
    salaryMax: 110000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "cloud-services",
    categoryId: "cat-operations",
    views: 78,
    publishedAt: new Date("2024-12-11"),
    expiresAt: new Date("2025-02-11"),
    createdAt: new Date("2024-12-11"),
    updatedAt: new Date("2024-12-13"),
  },
  
  // HR Jobs
  {
    id: "job-19",
    title: "HR Business Partner",
    slug: "hr-business-partner-19",
    description: "Partner with business leaders to develop HR strategies that support organizational goals. Provide guidance on employee relations, performance management, and organizational development. Support talent acquisition and retention initiatives.",
    requirements: "4+ years of HR generalist or business partner experience\n• Strong knowledge of employment law and HR best practices\n• Experience with HRIS systems\n• Excellent interpersonal and communication skills\n• Change management and organizational development experience\n• Bachelor's degree in HR, Business, or related field\n• PHR or SHRM certification preferred\n• Consulting and advisory skills",
    benefits: "• Competitive salary ($75k - $95k)\n• Comprehensive benefits package\n• Professional development and certification support\n• Flexible work schedule\n• HR conference attendance\n• Stock options\n• Collaborative HR team\n• Growth opportunities",
    location: "Austin, TX",
    remote: true,
    salaryMin: 75000,
    salaryMax: 95000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "tesla",
    categoryId: "cat-hr",
    views: 89,
    publishedAt: new Date("2024-12-10"),
    expiresAt: new Date("2025-02-10"),
    createdAt: new Date("2024-12-10"),
    updatedAt: new Date("2024-12-12"),
  },
  
  // Additional Technology Jobs
  {
    id: "job-20",
    title: "Software Engineer Intern",
    slug: "software-engineer-intern-20",
    description: "Join our engineering team as an intern to gain hands-on experience in software development. Work on real projects, learn from senior engineers, and contribute to our codebase. This is a great opportunity to start your career in technology.",
    requirements: "Currently pursuing Computer Science or related degree\n• Basic programming knowledge (any language)\n• Understanding of data structures and algorithms\n• Eagerness to learn and grow\n• Strong problem-solving skills\n• Good communication abilities\n• GPA of 3.0 or higher preferred\n• Previous internship or project experience a plus",
    benefits: "• Competitive internship stipend ($25/hour)\n• Mentorship from senior engineers\n• Real project experience\n• Full-time offer potential\n• Professional development opportunities\n• Flexible schedule around school\n• Team events and networking\n• Access to learning resources",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 25,
    salaryMax: 30,
    currency: "USD",
    jobType: "INTERNSHIP",
    experience: "ENTRY_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "meta",
    categoryId: "cat-tech",
    views: 145,
    publishedAt: new Date("2024-12-09"),
    expiresAt: new Date("2025-03-09"),
    createdAt: new Date("2024-12-09"),
    updatedAt: new Date("2024-12-11"),
  },
  
  // Contract/Freelance Jobs
  {
    id: "job-21",
    title: "Frontend Developer - Contract",
    slug: "frontend-developer-contract-21",
    description: "Short-term contract position to help build new features for our web application. Work with our existing team to implement designs and improve user experience. Perfect for freelancers looking for a 3-6 month engagement.",
    requirements: "3+ years of frontend development experience\n• Strong React and TypeScript skills\n• Experience with modern CSS and responsive design\n• Ability to work independently\n• Strong communication skills for remote collaboration\n• Portfolio of previous work\n• Available for 30+ hours per week\n• Experience with agile development processes",
    benefits: "• Competitive hourly rate ($60 - $80/hour)\n• Flexible schedule\n• Remote work\n• Potential for extension\n• Opportunity to work with modern tech stack\n• Collaborative team environment\n• Clear project scope and timeline\n• Quick decision making",
    location: "Remote",
    remote: true,
    salaryMin: 60,
    salaryMax: 80,
    currency: "USD",
    jobType: "CONTRACT",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "startup-ai",
    categoryId: "cat-frontend",
    views: 67,
    publishedAt: new Date("2024-12-08"),
    expiresAt: new Date("2025-01-08"),
    createdAt: new Date("2024-12-08"),
    updatedAt: new Date("2024-12-10"),
  },
  
  // Senior/Executive Level Jobs
  {
    id: "job-22",
    title: "Senior Engineering Manager",
    slug: "senior-engineering-manager-22",
    description: "Lead a team of 10+ engineers across multiple product areas. Drive technical strategy, mentor engineering talent, and collaborate with product and design teams to deliver exceptional software products. This role requires strong technical background and proven leadership experience.",
    requirements: "8+ years of software engineering experience\n• 3+ years of engineering management experience\n• Experience leading teams of 8+ engineers\n• Strong technical background in modern web technologies\n• Experience with agile development processes\n• Excellent communication and leadership skills\n• Bachelor's degree in Computer Science or equivalent\n• Experience with hiring and performance management",
    benefits: "• Competitive salary ($180k - $220k)\n• Significant equity package\n• Comprehensive benefits\n• Management development programs\n• Conference and training budget\n• Flexible work arrangements\n• Top-tier equipment\n• Sabbatical opportunities",
    location: "Seattle, WA",
    remote: true,
    salaryMin: 180000,
    salaryMax: 220000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "EXECUTIVE",
    status: "PUBLISHED",
    featured: true,
    companyId: "amazon",
    categoryId: "cat-tech",
    views: 201,
    publishedAt: new Date("2024-12-07"),
    expiresAt: new Date("2025-03-07"),
    createdAt: new Date("2024-12-07"),
    updatedAt: new Date("2024-12-09"),
  },
  
  // Part-time Jobs
  {
    id: "job-23",
    title: "Part-time UX Designer",
    slug: "part-time-ux-designer-23",
    description: "Part-time UX design role perfect for experienced designers looking for flexibility. Work 20-25 hours per week on exciting design projects. Collaborate with our team to create beautiful and functional user experiences.",
    requirements: "3+ years of UX design experience\n• Strong portfolio demonstrating design process\n• Proficiency in Figma and design tools\n• Experience with user research and testing\n• Available 20-25 hours per week\n• Strong communication skills\n• Ability to work independently\n• Bachelor's degree in Design or related field",
    benefits: "• Competitive hourly rate ($45 - $60/hour)\n• Flexible schedule\n• Remote work options\n• Access to design tools and resources\n• Collaborative design team\n• Opportunity for full-time transition\n• Professional development support\n• Creative freedom",
    location: "Portland, OR",
    remote: true,
    salaryMin: 45,
    salaryMax: 60,
    currency: "USD",
    jobType: "PART_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "design-studio",
    categoryId: "cat-design",
    views: 43,
    publishedAt: new Date("2024-12-06"),
    expiresAt: new Date("2025-02-06"),
    createdAt: new Date("2024-12-06"),
    updatedAt: new Date("2024-12-08"),
  },
  
  // More diverse industry jobs
  {
    id: "job-24",
    title: "Robotics Engineer",
    slug: "robotics-engineer-24",
    description: "Design and develop robotic systems for industrial applications. Work with mechanical, electrical, and software components to create innovative automation solutions. Collaborate with cross-functional teams to bring robotic products to market.",
    requirements: "4+ years of robotics engineering experience\n• Strong background in mechanical or electrical engineering\n• Programming experience in C++, Python, or ROS\n• Knowledge of control systems and sensors\n• CAD software proficiency (SolidWorks, AutoCAD)\n• Experience with embedded systems\n• Master's degree in Robotics, Engineering, or related field\n• Problem-solving and debugging skills",
    benefits: "• Competitive salary ($100k - $130k)\n• Research and development opportunities\n• Access to cutting-edge robotics lab\n• Patent bonuses\n• Professional development budget\n• Health and dental benefits\n• Stock options\n• Flexible work schedule",
    location: "Pittsburgh, PA",
    remote: false,
    salaryMin: 100000,
    salaryMax: 130000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "robotics-lab",
    categoryId: "cat-tech",
    views: 156,
    publishedAt: new Date("2024-12-05"),
    expiresAt: new Date("2025-03-05"),
    createdAt: new Date("2024-12-05"),
    updatedAt: new Date("2024-12-07"),
  },
  {
    id: "job-25",
    title: "Biotechnology Research Scientist",
    slug: "biotechnology-research-scientist-25",
    description: "Conduct cutting-edge research in biotechnology to develop new treatments and diagnostic tools. Design experiments, analyze data, and collaborate with multidisciplinary teams to advance scientific knowledge and product development.",
    requirements: "PhD in Biology, Biochemistry, or related field\n• 2+ years of postdoctoral or industry research experience\n• Strong background in molecular biology techniques\n• Experience with data analysis and statistical software\n• Publication record in peer-reviewed journals\n• Laboratory management experience\n• Excellent written and verbal communication skills\n• Grant writing experience preferred",
    benefits: "• Competitive salary ($90k - $120k)\n• Research sabbatical opportunities\n• Access to state-of-the-art laboratory facilities\n• Conference presentation and publication support\n• Health and wellness benefits\n• Stock options\n• Professional development budget\n• Collaborative research environment",
    location: "Cambridge, MA",
    remote: false,
    salaryMin: 90000,
    salaryMax: 120000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "biotech-solutions",
    categoryId: "cat-healthcare",
    views: 78,
    publishedAt: new Date("2024-12-04"),
    expiresAt: new Date("2025-03-04"),
    createdAt: new Date("2024-12-04"),
    updatedAt: new Date("2024-12-06"),
  },
  
  // Additional jobs to reach 50+ total
  {
    id: "job-26",
    title: "Growth Marketing Manager",
    slug: "growth-marketing-manager-26",
    description: "Drive user acquisition and retention through data-driven marketing strategies. Experiment with new channels, optimize conversion funnels, and scale successful campaigns. Work closely with product and analytics teams to achieve growth targets.",
    requirements: "3+ years of growth marketing experience\n• Strong analytical skills and data-driven mindset\n• Experience with A/B testing and experimentation\n• Knowledge of marketing analytics tools\n• SEM, SEO, and social media advertising experience\n• Understanding of conversion optimization\n• Bachelor's degree in Marketing, Business, or related field\n• Experience with growth hacking techniques",
    benefits: "• Competitive salary ($85k - $110k)\n• Performance-based bonuses\n• Stock options\n• Marketing tools and budget\n• Professional development opportunities\n• Flexible work arrangements\n• Health and dental benefits\n• Growth-focused team environment",
    location: "Austin, TX",
    remote: true,
    salaryMin: 85000,
    salaryMax: 110000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "MID_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "ecommerce-plus",
    categoryId: "cat-marketing",
    views: 94,
    publishedAt: new Date("2024-12-03"),
    expiresAt: new Date("2025-02-03"),
    createdAt: new Date("2024-12-03"),
    updatedAt: new Date("2024-12-05"),
  },
  {
    id: "job-27",
    title: "Legal Counsel",
    slug: "legal-counsel-27",
    description: "Provide legal guidance and support across various business functions. Review contracts, ensure regulatory compliance, and manage legal risks. Work with external counsel and support corporate governance activities.",
    requirements: "JD from accredited law school\n• 3+ years of corporate law experience\n• Bar admission in relevant jurisdiction\n• Experience with contract negotiation and drafting\n• Knowledge of employment and corporate law\n• Strong analytical and communication skills\n• Technology industry experience preferred\n• In-house counsel experience a plus",
    benefits: "• Competitive salary ($120k - $150k)\n• Comprehensive benefits package\n• Bar association membership support\n• Continuing legal education budget\n• Flexible work arrangements\n• Stock options\n• Professional development opportunities\n• Collaborative legal team",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 120000,
    salaryMax: 150000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "techcorp",
    categoryId: "cat-legal",
    views: 67,
    publishedAt: new Date("2024-12-02"),
    expiresAt: new Date("2025-02-02"),
    createdAt: new Date("2024-12-02"),
    updatedAt: new Date("2024-12-04"),
  },
  {
    id: "job-28",
    title: "Business Development Manager",
    slug: "business-development-manager-28",
    description: "Identify and pursue new business opportunities to drive company growth. Build strategic partnerships, negotiate deals, and develop go-to-market strategies for new products and services.",
    requirements: "4+ years of business development experience\n• Proven track record of closing deals\n• Strong networking and relationship building skills\n• Experience with B2B sales and partnerships\n• Strategic thinking and market analysis abilities\n• Excellent presentation and negotiation skills\n• MBA preferred\n• Travel flexibility for client meetings",
    benefits: "• Competitive base salary plus commission ($90k - $130k OTE)\n• Stock options\n• Travel and entertainment budget\n• Health and dental benefits\n• Professional development support\n• Flexible work schedule\n• Performance bonuses\n• Growth opportunities",
    location: "Chicago, IL",
    remote: true,
    salaryMin: 90000,
    salaryMax: 130000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "consulting-group",
    categoryId: "cat-sales",
    views: 108,
    publishedAt: new Date("2024-12-01"),
    expiresAt: new Date("2025-02-01"),
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2024-12-03"),
  },
  {
    id: "job-29",
    title: "Cloud Solutions Architect",
    slug: "cloud-solutions-architect-29",
    description: "Design and implement cloud infrastructure solutions for enterprise clients. Lead technical discussions, create architecture diagrams, and ensure scalable and secure cloud deployments.",
    requirements: "5+ years of cloud architecture experience\n• Deep knowledge of AWS, Azure, or GCP\n• Experience with infrastructure as code\n• Strong understanding of networking and security\n• Enterprise architecture experience\n• Cloud certifications (AWS Solutions Architect, etc.)\n• Excellent communication and presentation skills\n• Bachelor's degree in Computer Science or related field",
    benefits: "• Competitive salary ($130k - $160k)\n• Cloud certification reimbursement\n• Conference and training budget\n• Stock options\n• Health and wellness benefits\n• Remote work flexibility\n• Professional development opportunities\n• Technical leadership role",
    location: "Dallas, TX",
    remote: true,
    salaryMin: 130000,
    salaryMax: 160000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: true,
    companyId: "cloud-services",
    categoryId: "cat-devops",
    views: 187,
    publishedAt: new Date("2024-11-30"),
    expiresAt: new Date("2025-02-28"),
    createdAt: new Date("2024-11-30"),
    updatedAt: new Date("2024-12-02"),
  },
  {
    id: "job-30",
    title: "Senior Data Engineer",
    slug: "senior-data-engineer-30",
    description: "Build and maintain data pipelines and infrastructure that power our analytics and machine learning systems. Work with large-scale data processing and ensure data quality and reliability.",
    requirements: "4+ years of data engineering experience\n• Strong programming skills in Python and SQL\n• Experience with big data technologies (Spark, Kafka, Airflow)\n• Knowledge of cloud data platforms (Snowflake, BigQuery)\n• ETL/ELT pipeline development experience\n• Understanding of data warehousing concepts\n• Experience with containerization and orchestration\n• Bachelor's degree in Computer Science or related field",
    benefits: "• Competitive salary ($115k - $145k)\n• Stock options\n• Health and dental benefits\n• Data platform access and training\n• Conference attendance opportunities\n• Flexible work arrangements\n• Professional development budget\n• Collaborative data team",
    location: "Minneapolis, MN",
    remote: true,
    salaryMin: 115000,
    salaryMax: 145000,
    currency: "USD",
    jobType: "FULL_TIME",
    experience: "SENIOR_LEVEL",
    status: "PUBLISHED",
    featured: false,
    companyId: "data-analytics",
    categoryId: "cat-data",
    views: 134,
    publishedAt: new Date("2024-11-29"),
    expiresAt: new Date("2025-01-29"),
    createdAt: new Date("2024-11-29"),
    updatedAt: new Date("2024-12-01"),
  },
]